config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  devise_for :users

  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :users
  resources :group_chats
  resources :group_members
  resources :tags
  resources :tag_lists
  get 'user/belong_to_group/:id' => 'users#belong_to_group', as: 'belong_to_group'
  get 'group/chat/:id' => 'groups#chat', as: 'chat_room'
  get 'search' => 'searches#search', as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_members, dependent: :destroy
    has_many :users, through: :group_users, dependent: :destroy

    def self.looks(search, word)
        if search == "perfect_match"
          @group = Group.where("name LIKE?","#{word}")
        elsif search == "forward_match"
          @group = Group.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @group = Group.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @group = Group.where("name LIKE?","%#{word}%")
        else
          @group = Group.all
        end
    end
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :group
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  def self.looks(search, word)
    if search == "perfect_match"
      @tag = Tag.where("tag LIKE?","#{word}")
    elsif search == "forward_match"
      @tag = Tag.where("tag LIKE?","#{word}%")
    elsif search == "backward_match"
      @tag = Tag.where("tag LIKE?","%#{word}")
    elsif search == "partial_match"
      @tag = Tag.where("tag LIKE?","%#{word}%")
    else
      @tag = Tag.all
    end
  end
end

app/models/tag_list.rb
class TagList < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました。'
    else
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @group_member = GroupMember.new
    @group_members = GroupMember.where(group_id: @group.id)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
        redirect_to groups_path, notice: 'グループを更新しました。'
    else
        render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      redirect_to root_path, notice: 'グループを削除しました。'
    end
  end

  def chat
    @group = Group.find(params[:id])
    @group_chats = GroupChat.where(group_id: @group.id)
    @group_chat = GroupChat.new
  end

  private

  def group_params
    params.require(:group).permit(:name, :explain, :leader_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    elsif @range == "Group"
      @groups = Group.looks(params[:search], params[:word])
    else
      @tags = Tag.looks(params[:search], params[:word])
    end

    render 'index'
  end

end

app/controllers/tag_lists_controller.rb
class TagListsController < ApplicationController
  def new
    @tag_list = TagList.new
  end

  def create
    @tag_list = TagList.new(tag_list_params)
    @tag_list.save
  end

  def destroy
    @tag_list = TagList.find(params[:id])
    @tag_list.destroy
  end

  private

  def tag_list_params
    params.require(:tag_list).permit(:tag_id,:group_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private

  def tag_params
    params.require(:tag).permit(:tag)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def belong_to_group
    @user = User.find(params[:id])
    @group_members = GroupMember.where(user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:id])
    redirect_to destroy_session_path(@user)
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

app/helpers/group_member_helper.rb
module GroupMemberHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tag_lists_helper.rb
module TagListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/chat.html.erb
<div class="container">
  <div class="row">
    <div class="col-1">
    </div>
       <h6 class="d-flex justify-content-left mb-5 bg-secondary p-2 text-black bg-opacity-10">チャット</h6>
  </div>


          <% @group_chats.reverse_each do |chat| %>
            <div class="row">
              <div class = "col-md-2 bg-success">
                <%= User.find(chat.user_id).name %>
              </div>
              <div class = "col-md-5 offset-md-1 ">
                <%= chat.chat %>
              </div>
              <div class = "col-md-2">
                <%= l chat.created_at %>
              </div>
              <% if chat.user_id == current_user.id || current_user.admin %>
                <%=  link_to "削除する", group_chat_path(chat.id), method: :delete, class: 'btn btn-sm btn-danger col-sm-1 mx-auto' %>
              <% end %>
            </div>
              <br>
          <% end %>

      <%= form_with model: @group_chat,url: group_chats_path do |f| %>
        <div class="form-group">
          <%= f.hidden_field :group_id, :value => @group.id %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.text_area :chat, placeholder: "チャット" %>
          <%= f.submit '送信', class: 'btn btn-success' %>
        </div>
      <% end %>
</div>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <h2>サークル編集</h2>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @group do |f| %>
        <div class="form-group">
          <%= f.label :name, "サークル名" %>
          <%= f.text_field :name, placeholder: "サークル名" %>
        </div>
        <div class="form-group">
          <%= f.label :explain, "サークル紹介文" %>
          <%= f.text_area :explain, placeholder: @group.explain %>
        </div>
        <%= f.hidden_field :leader_id, :value => current_user.id %>

          <%= f.submit '更新', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">


  <div>
    <h3 class = "col-md-4 offset-md-1 bg-light">サークル一覧</h2>
     <table class = "table">

      <thead>
       <tr class=" table-secondary ">
        <th>サークル名</th>
        <th>紹介文</th>
        <th>リーダー</th>
       </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
         <tr>
            <td>
            <%= link_to group_path(group),class: 'nav-link' do %>
              <%= group.name %>
            <% end %>
            </td>
            <td>
              <%= group.explain %>
            </td>
            <td><%= User.find(group.leader_id).name %></td>
         </tr>
        <% end %>
     </tbody>

   </table>
  </div>
 </div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <h2>新規サークル作成</h2>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @group do |f| %>
        <div class="form-group">
          <%= f.label :name, "サークル名" %>
          <%= f.text_field :name, placeholder: "サークル名" %>
        </div>
        <!-- タグ機能は後で追加 -->
        <!--<div class="form-group">-->
        <!--  <= f.label :tag_list_id, "タグ" %>-->
        <!--  <= f.collection_select :tag_id, Genre.all, :id, :name, prompt: "--選択してください--" %>-->
        <!--</div>-->
        <div class="form-group">
          <%= f.label :explain, "サークル紹介文" %>
          <%= f.text_area :explain, placeholder: "ここに紹介文を記述します" %>
        </div>
        <%= f.hidden_field :leader_id, :value => current_user.id %>

          <%= f.submit '新規作成', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <h2>サークル詳細</h2>
  </div>
  <div class="row">
    <div class="col-sm-7">
      <table>
        <tr>
          <td class = "col-sm-5">サークル名</td>
          <td class = "col-sm-7"><%= @group.name %></td>
        </tr>
        <tr>
          <td class = "col-sm-5">サークル説明</td>
          <td class = "col-sm-7"><%= @group.explain %></td>
        </tr>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <% if @group.leader_id == current_user.id || current_user.admin %>
    <div class="row my-3">
      <div class = "col-md-7">
        <%=  link_to "編集する", edit_group_path(@group.id), class: 'btn btn-sm btn-success col-sm-3 mx-auto' %>
        <%=  link_to "解散する", group_path(@group.id), method: :delete, class: 'btn btn-sm btn-danger col-sm-3 mx-auto' %>
      </div>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <% if group_member = GroupMember.find_by(user_id: current_user.id , group_id: @group.id)|| current_user.admin || current_user.id == @group.leader_id %>

      <% if current_user.admin == false && current_user.id != @group.leader_id %>
        <div class = "col-md-7">
          <%=  link_to "脱退する", group_member_path(group_member.id), method: :delete, class: 'btn btn-sm btn-danger col-sm-3 mx-auto' %>
          <%=  link_to "  チャットへ", chat_room_path(@group.id), class: 'btn btn-sm btn-success col-sm-3 mx-auto' %>
        </div>
      <% else %>
        <div class = "col-md-6">
          <%=  link_to "  チャットへ", chat_room_path(@group.id), class: 'btn btn-sm btn-success col-sm-3 mx-auto' %>
        </div>
      <% end %>
    <% elsif current_user.id != @group.leader_id %>
      <%= form_with model: @group_member, url:group_members_path do |f| %>
        <div class="form-group">
          <%= f.hidden_field :group_id, :value => @group.id %>
          <%= f.submit 'メンバーになる'%>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="row">
    <h2>メンバー一覧</h2>
  </div>
  <div class = "row">
    <div class = "col-md-4">リーダー</div>
    <div class = "col-md-4">
      <%=  link_to user_path(@group.leader_id) do %>
        <%= User.find(@group.leader_id).name %><br>
      <% end %>
    </div>
  </div>
  <div class = "row">
    <div class="col-md-4">メンバー</div>
  </div>

  <% @group_members.each do |member| %>
    <div class = "row">
      <div class="col-md-4 offset-md-4">
        <%=  link_to user_path(member.user_id) do %>
          <%= User.find(member.user_id).name %><br>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/users/belong_to_group.html.erb
<div class="container">


  <div>
    <h3 class = "col-md-4 offset-md-1 bg-light">所属サークル一覧</h2>
     <table class = "table">

      <thead>
       <tr class=" table-secondary ">
        <th>サークル名</th>
        <th>紹介文</th>
        <th>リーダー</th>
       </tr>
      </thead>
      <tbody>
        <% @group_members.each do |group| %>
         <tr>
            <td>
            <%= link_to group_path(group.group_id),class: 'nav-link' do %>
              <%= Group.find(group.group_id).name %>
            <% end %>
            </td>
            <td>
              <%= Group.find(group.group_id).explain %>
            </td>
            <td><%= User.find(Group.find(group.group_id).leader_id).name %></td>
         </tr>
        <% end %>
     </tbody>

   </table>
  </div>
 </div>

app/views/users/edit.html.erb
  <div class = "container">
    <div class = "col-md-8">
     <h2>会員情報編集</h2>
     <table class="table table-hover table-inverse">

      <tbody>
        <%= form_with model: @user do |f| %>
        <tr>
          <td>ユーザーネーム</td>
          <td><%= f.text_field :name, class:'form-control name' %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email, class:'form-control email' %></td>
        </tr>

       <div class="form-group">
        <%= f.submit "編集内容を保存", class:"btn btn-secondary" %>
       </div>
      <% end %>

  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1">
    </div>
       <h6 class="d-flex justify-content-left mb-5 bg-secondary p-2 text-black bg-opacity-10">会員一覧</h6>
  </div>

      <table class='table'>
        <thead　class='thead-light'>
          <tr>
            <th>メンバー名</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <% if user.admin == false %>
              <tr>
                <td>
                  <%=  link_to user_path(user.id),class: 'nav-link' do %>
                    <%= user.name %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
       <h6 class="d-flex justify-content-left mb-5 bg-secondary p-2 text-black bg-opacity-10">マイページ</h6>
  </div>
  <% if @user ==  current_user || current_user.admin %>
    <%= link_to "編集する", edit_user_path, class: "col-1 btn btn-sm btn-success" %>
  <% end %>
  <table border="1">
    <tr>
      <td bgcolor="#cococo" width="20%">ユーザーネーム</td>
      <td width="60%"><%= @user.name%></td>
    <% if @user ==  current_user || current_user.admin %>
      <tr>
        <td bgcolor="#cococo">メールアドレス</td>
        <td><%= @user.email %></td>
      </tr>
    <% end %>
  </table>
  <div class="field row mb-2">
    <%= link_to "所属グループ一覧を見る", belong_to_group_path(@user.id), class: "col-9 btn btn-sm btn-success" %>
  </div>
</div>