config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  devise_for :users

  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :users
  resources :group_chats
  resources :group_members
  resources :tags
  resources :tag_lists
  get 'user/belong_to_group/:id' => 'users#belong_to_group', as: 'belong_to_group'
  get 'group/chat/:id' => 'groups#chat', as: 'chat_room'
  get 'search' => 'searches#search', as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_members, dependent: :destroy
    has_many :users, through: :group_users, dependent: :destroy

    def self.looks(search, word)
        if search == "perfect_match"
          @group = Group.where("name LIKE?","#{word}")
        elsif search == "forward_match"
          @group = Group.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
          @group = Group.where("name LIKE?","%#{word}")
        elsif search == "partial_match"
          @group = Group.where("name LIKE?","%#{word}%")
        else
          @group = Group.all
        end
    end
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :group
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  def self.looks(search, word)
    if search == "perfect_match"
      @tag = Tag.where("tag LIKE?","#{word}")
    elsif search == "forward_match"
      @tag = Tag.where("tag LIKE?","#{word}%")
    elsif search == "backward_match"
      @tag = Tag.where("tag LIKE?","%#{word}")
    elsif search == "partial_match"
      @tag = Tag.where("tag LIKE?","%#{word}%")
    else
      @tag = Tag.all
    end
  end
end

app/models/tag_list.rb
class TagList < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private

  def tag_params
    params.require(:tag).permit(:tag)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def belong_to_group
    @user = User.find(params[:id])
    @group_members = GroupMember.where(user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:id])
    redirect_to destroy_session_path(@user)
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

app/helpers/group_member_helper.rb
module GroupMemberHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tag_lists_helper.rb
module TagListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="border-bottom border-dark">
  <nav class="navbar navbar-expand-lg navbar-white bg-white">
    <div class="container">
      <%=  link_to root_path,class: 'nav-link' do %>
        <div><%= image_tag "logo.png", size: '150x75'%></div>
      <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"></button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ">


            <% if user_signed_in? %>
              <li>
                <%= link_to destroy_session_path(current_user), method: :delete,class: 'nav-link text-light' do %>
                  <button type="button" class="btn btn-light btn-sm"><p class="small">ログアウト</p></button>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                  <button type="button" class="btn btn-light btn-sm">ログイン</button>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                  <button type="button" class="btn btn-light btn-sm">新規登録</button>
                <% end %>
              </li>
            <% end %>

            <li>
              <% if user_signed_in? %>
                <%= link_to new_group_path, class: 'nav-link text-light' do %>
                  <button type="button" class="btn btn-light btn-sm"><p class="small">サークル作成</p></button>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to groups_path ,class: 'nav-link text-light' do %>
                <button type="button" class="btn btn-light btn-sm">サークル一覧</button>
              <% end %>
            </li>

            <li>
              <%= link_to users_path ,class: 'nav-link text-light' do %>
                <button type="button" class="btn btn-light btn-sm">メンバー一覧</button>
              <% end %>
            </li>
            <li>
              <% if user_signed_in? %>
                <div class="search_form">
                  <%= form_with url: search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :range, options_for_select([["ユーザー",'User'], ['サークル','Group'],['タグ','Tag']]) %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn btn-primary" %>
                  <% end %>
                </div>
              <% end %>
            </li>

           </ul>
          </div>
        </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OctClique</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
  </body>
</html>